# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
loader_version=0.18.2
loom_version=1.14-SNAPSHOT

# Mod Properties
mod_version=0.2.0
maven_group=ru.stylemod
archives_base_name=style-mod

# Dependencies
fabric_api_version=0.141.6+1.21.11
